#define _POSIX_C_SOURCE 200809L
#include "stream.h"

#include <dirent.h>
#include <errno.h>
#include <fcntl.h>
#include <limits.h>
#include <pthread.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <time.h>
#include <unistd.h>

/* O_NOFOLLOW is available on the supported macOS/Linux builds. Keeping the
 * fallback lets standalone sanitizer builds compile on SDKs that hide it
 * without the platform feature macro; the regular build enables that macro. */
#ifndef O_NOFOLLOW
#define O_NOFOLLOW 0
#endif

enum { S_DECLARE = 1, S_APPEND = 2, S_COMMIT = 3, S_TRIM = 4, S_APPEND_BATCH = 5,
       S_APPEND_KEY = 6, S_APPEND_BATCH_KEY = 7, S_DELETE = 8,
       S_RETENTION = 9, S_REVISION = 10, S_IDENTITY = 11 };
/* The body precedes the key in the flexible tail so existing body-oriented
 * paths retain their compact layout.  Keyed records use additive WAL opcodes;
 * old logs and unkeyed appends keep their original wire representation. */
typedef struct StreamRecord { struct StreamRecord *next; uint64_t offset, at_ms; uint32_t len; uint16_t key_len; unsigned char data[]; } StreamRecord;
typedef struct StreamPart { StreamRecord *head, *tail; uint64_t base, next, bytes; } StreamPart;
typedef struct StreamMember { struct StreamMember *next; uint64_t owner, deadline_ms; } StreamMember;
typedef struct StreamGroup { struct StreamGroup *next; char *name; uint32_t len; uint64_t *offsets; StreamMember *members; uint32_t member_count; uint64_t generation; } StreamGroup;
typedef struct StreamTopic { struct StreamTopic *next; char *name; uint32_t len, partitions; uint64_t max_bytes, max_age_ms, bytes, records, revision; unsigned char id[STREAM_ID_LEN]; int id_persisted; StreamPart *parts; StreamGroup *groups; } StreamTopic;
/* `live_bytes` mirrors, incrementally, the full-traversal estimate of the WAL
 * bytes a checkpoint rewrite would need: per topic 22+len, per retained
 * record 35+t->len+r->len, per group partitions*(25+t->len+g->len). It is
 * updated only at the shared mutation points (add_topic, append/part_link,
 * trim_part, group creation), so compaction eligibility checks are O(1)
 * instead of scanning every retained record.
 *
 * Group commit: `wal_seq` counts WAL records written, `synced_seq` is the
 * high-water mark known durable (covered by a completed fsync). Durable
 * operations write their record(s) and apply the in-memory mutation under
 * the store lock, then wait for `synced_seq` to reach their sequence with
 * the lock RELEASED; one thread at a time (`syncer`) fsyncs the high-water
 * mark outside the lock, so a single fsync covers every writer that arrived
 * during the previous round. Because all records share one sequential WAL,
 * a record's durability implies the durability of every earlier record, so
 * a client-visible acknowledgement never precedes its fsync point. A write
 * or fsync failure sets `failed` permanently and wakes every waiter with an
 * error: durable work fails closed. */
struct StreamStore { pthread_mutex_t mu; pthread_cond_t sync_cond; StreamTopic *topics; int fd, failed, syncer; char *path; uint64_t wal_bytes, live_bytes, wal_seq, synced_seq, sync_target;
  /* WAL staging and space reservation, all guarded by `mu` (see the queue
   * engine, which made the same change first). Records are assembled in
   * `wal_buf` and issued as one `pwrite` instead of a write per field;
   * `wal_off` is an explicit append cursor rather than O_APPEND. */
  unsigned char *wal_buf; size_t wal_buf_len, wal_buf_cap; off_t wal_off; };

#define STREAM_WAL_BUF_CAP (256u * 1024u)

#define STREAM_COMPACT_FLOOR (1ull << 20)

/* Slice-by-8 over the same reflected polynomial: eight input bytes fold per
 * step and the value is bit-identical to the byte-at-a-time routine, so
 * existing stream WAL files verify unchanged. */
static uint32_t crc_table[8][256];
static pthread_once_t crc_once = PTHREAD_ONCE_INIT;
static void crc_init(void) { for (uint32_t i=0;i<256;i++) { uint32_t x=i; for(int j=0;j<8;j++) x=x&1?(x>>1)^0xedb88320u:x>>1; crc_table[0][i]=x; }
  for (uint32_t i=0;i<256;i++) for (int k=1;k<8;k++) crc_table[k][i]=crc_table[0][crc_table[k-1][i]&0xff]^(crc_table[k-1][i]>>8); }
static uint32_t crc32(const void *p, size_t n) { pthread_once(&crc_once, crc_init); uint32_t c=~0u; const unsigned char *s=p;
  while (n>=8) { uint32_t lo=(uint32_t)s[0]|((uint32_t)s[1]<<8)|((uint32_t)s[2]<<16)|((uint32_t)s[3]<<24); lo^=c;
    c=crc_table[7][lo&0xff]^crc_table[6][(lo>>8)&0xff]^crc_table[5][(lo>>16)&0xff]^crc_table[4][(lo>>24)&0xff]
      ^crc_table[3][s[4]]^crc_table[2][s[5]]^crc_table[1][s[6]]^crc_table[0][s[7]]; s+=8; n-=8; }
  while (n--) { c=crc_table[0][(c^*s++)&255]^(c>>8); }
  return ~c; }
static void u16(unsigned char *p,uint16_t x){p[0]=x;p[1]=x>>8;} static uint16_t g16(const unsigned char*p){return (uint16_t)p[0]|((uint16_t)p[1]<<8);} static void u32(unsigned char*p,uint32_t x){for(int i=0;i<4;i++)p[i]=(unsigned char)(x>>(8*i));} static uint32_t g32(const unsigned char*p){uint32_t x=0;for(int i=3;i>=0;i--)x=(x<<8)|p[i];return x;} static void u64(unsigned char*p,uint64_t x){for(int i=0;i<8;i++)p[i]=(unsigned char)(x>>(8*i));} static uint64_t g64(const unsigned char*p){uint64_t x=0;for(int i=7;i>=0;i--)x=(x<<8)|p[i];return x;}
static uint64_t now_ms(void){struct timespec t;clock_gettime(CLOCK_REALTIME,&t);return (uint64_t)t.tv_sec*1000+t.tv_nsec/1000000;}
static uint64_t mono_ms(void){struct timespec t;clock_gettime(CLOCK_MONOTONIC,&t);return (uint64_t)t.tv_sec*1000+t.tv_nsec/1000000;}
/* 128-bit topic incarnation from the OS secure random source; the documented
 * fallback only keeps declaration alive on systems without a random device
 * (not among the supported platforms). */
static void topic_id_generate(unsigned char out[STREAM_ID_LEN]){unsigned char raw[STREAM_ID_LEN];size_t used=0;int fd=open("/dev/urandom",O_RDONLY|O_CLOEXEC);while(fd>=0&&used<sizeof raw){ssize_t r=read(fd,raw+used,sizeof raw-used);if(r>0)used+=(size_t)r;else if(r<0&&errno==EINTR)continue;else break;}if(fd>=0)close(fd);if(used!=sizeof raw){uint64_t seed=(uint64_t)time(NULL)^((uint64_t)getpid()<<32)^(uintptr_t)out;for(size_t i=0;i<sizeof raw;i++){seed=seed*6364136223846793005ULL+1;raw[i]=(unsigned char)(seed>>32);}}memcpy(out,raw,STREAM_ID_LEN);}
static int write_all(int fd,const void*p,size_t n){const unsigned char*b=p;while(n){ssize_t r=write(fd,b,n);if(r<0&&errno==EINTR)continue;if(r<=0)return-1;b+=r;n-=(size_t)r;}return 0;}
static int write_record_fd(int fd,unsigned char op,const void*body,uint32_t n,int sync){unsigned char h[9];h[0]=op;u32(h+1,n);uint32_t c=crc32(&op,1)^crc32(body,n);u32(h+5,c);return write_all(fd,h,sizeof h)||write_all(fd,body,n)||(sync&&fsync(fd))?-1:0;}
static int pwrite_all(int fd,const void*p,size_t n,off_t off){const unsigned char*b=p;while(n){ssize_t r=pwrite(fd,b,n,off);if(r<0&&errno==EINTR)continue;if(r<=0)return-1;b+=r;off+=r;n-=(size_t)r;}return 0;}
/* Hand every staged byte to the kernel. Caller holds `mu`. */
static int wal_flush_locked(StreamStore*s){
  if(!s->wal_buf_len)return 0;
  if(pwrite_all(s->fd,s->wal_buf,s->wal_buf_len,s->wal_off))return-1;
  s->wal_off+=(off_t)s->wal_buf_len;s->wal_buf_len=0;return 0;}
static int wal_sync_run(StreamStore*s){return fsync(s->fd);}
/* Stage one record. A record too large for the buffer is written directly
 * after flushing, so byte order still equals record order. Caller holds `mu`. */
static int wal_stage_locked(StreamStore*s,unsigned char op,const void*body,uint32_t n){
  unsigned char h[9];h[0]=op;u32(h+1,n);u32(h+5,crc32(&op,1)^crc32(body,n));
  size_t total=sizeof h+n;
  if(!s->wal_buf&&total<=STREAM_WAL_BUF_CAP){s->wal_buf=malloc(STREAM_WAL_BUF_CAP);if(s->wal_buf)s->wal_buf_cap=STREAM_WAL_BUF_CAP;}
  if(!s->wal_buf||total>s->wal_buf_cap){
    if(wal_flush_locked(s))return-1;
    if(pwrite_all(s->fd,h,sizeof h,s->wal_off)||(n&&pwrite_all(s->fd,body,n,s->wal_off+(off_t)sizeof h)))return-1;
    s->wal_off+=(off_t)total;return 0;}
  if(s->wal_buf_len+total>s->wal_buf_cap&&wal_flush_locked(s))return-1;
  memcpy(s->wal_buf+s->wal_buf_len,h,sizeof h);
  if(n)memcpy(s->wal_buf+s->wal_buf_len+sizeof h,body,n);
  s->wal_buf_len+=total;return 0;}
/* Write one WAL record WITHOUT syncing; durability is provided by the group
 * fsync in stream_wait_durable_locked. Each record advances wal_seq. */
/* Stage and hand to the kernel before returning. Callers apply the record to
 * memory as soon as this succeeds, so a write error has to be visible now:
 * deferring it past the mutation would leave a record readable that no
 * barrier will ever cover. The staging buffer still turns the header and the
 * body into one syscall instead of two. */
static int log_record(StreamStore*s,unsigned char op,const void*body,uint32_t n){if(s->fd<0)return 0;if(wal_stage_locked(s,op,body,n)||wal_flush_locked(s)){s->failed=1;pthread_cond_broadcast(&s->sync_cond);return-1;}s->wal_bytes+=9u+n;s->wal_seq++;return 0;}
/* Block until `target` is durable (an fsync covers it) or the store fails.
 * Called with the lock held; the lock is released while fsync runs so
 * writers and readers proceed concurrently. The thread that finds no sync in
 * flight becomes the syncer and covers the current high-water mark, so under
 * concurrency one fsync completes many operations. */
static int stream_wait_durable_locked(StreamStore*s,uint64_t target){for(;;){if(s->failed)return-1;if(s->synced_seq>=target)return 0;if(s->syncer){pthread_cond_wait(&s->sync_cond,&s->mu);continue;}s->syncer=1;s->sync_target=s->wal_seq;
  /* The staged bytes for sync_target reach the file before the lock is
   * released; anything staged during the barrier belongs to a later round. */
  if(wal_flush_locked(s)){s->syncer=0;s->failed=1;pthread_cond_broadcast(&s->sync_cond);return-1;}
  pthread_mutex_unlock(&s->mu);int rc=wal_sync_run(s);pthread_mutex_lock(&s->mu);s->syncer=0;if(rc){s->failed=1;pthread_cond_broadcast(&s->sync_cond);return-1;}if(s->sync_target>s->synced_seq)s->synced_seq=s->sync_target;pthread_cond_broadcast(&s->sync_cond);}}
static int fsync_parent(const char *path){char b[PATH_MAX];size_t n=strlen(path);if(n>=sizeof b)return-1;memcpy(b,path,n+1);char *slash=strrchr(b,'/');const char *dir=".";if(slash){if(slash==b)slash[1]=0;else *slash=0;dir=b;}int fd=open(dir,O_RDONLY|O_DIRECTORY);if(fd<0)return-1;int rc=fsync(fd);if(close(fd))rc=-1;return rc;}
static StreamTopic *topic(StreamStore*s,const char*n,uint32_t l){for(StreamTopic*t=s->topics;t;t=t->next)if(t->len==l&&!memcmp(t->name,n,l))return t;return NULL;}
static void free_topic(StreamTopic*t){while(t){StreamTopic*n=t->next;for(uint32_t i=0;i<t->partitions;i++){StreamRecord*r=t->parts[i].head;while(r){StreamRecord*x=r->next;free(r);r=x;}}free(t->parts);while(t->groups){StreamGroup*g=t->groups;t->groups=g->next;while(g->members){StreamMember*m=g->members;g->members=m->next;free(m);}free(g->name);free(g->offsets);free(g);}free(t->name);free(t);t=n;}}
static int add_topic(StreamStore*s,const char*n,uint32_t l,uint32_t parts,uint64_t maxb,uint64_t age){if(!l||l>STREAM_NAME_MAX||!parts||parts>STREAM_PARTITIONS_MAX)return-1;StreamTopic*t=topic(s,n,l);if(t)return t->partitions==parts&&t->max_bytes==maxb&&t->max_age_ms==age?0:-1;t=calloc(1,sizeof*t);if(!t)return-1;t->name=malloc(l);t->parts=calloc(parts,sizeof* t->parts);if(!t->name||!t->parts){free_topic(t);return-1;}memcpy(t->name,n,l);t->len=l;t->partitions=parts;t->max_bytes=maxb;t->max_age_ms=age;t->revision=1;topic_id_generate(t->id);/* The provisional identity becomes durable when its S_IDENTITY record is
 * written: at declaration time together with S_DECLARE, or during the
 * store-open upgrade pass for legacy declarations. Replayed S_IDENTITY
 * records overwrite the provisional value, so replay never regenerates an
 * identity that already exists. */t->next=s->topics;s->topics=t;s->live_bytes+=22u+l;return 0;}
/* Shared per-record link path for single and batch appends; keeps the
 * retained-record counter and the incremental live estimate exact. */
static uint64_t record_bytes(const StreamRecord*r){return (uint64_t)r->len+r->key_len;}
static uint64_t record_live(const StreamTopic*t,const StreamRecord*r){return 35u+t->len+r->len+(r->key_len?2u+r->key_len:0u);}
static uint64_t identity_live(const StreamTopic*t){return 18u+t->len;}
static uint64_t topic_live(const StreamTopic*t){uint64_t live=22u+t->len+(t->id_persisted?identity_live(t):0);for(uint32_t p=0;p<t->partitions;p++)for(StreamRecord*r=t->parts[p].head;r;r=r->next)live+=record_live(t,r);for(StreamGroup*g=t->groups;g;g=g->next)live+=(uint64_t)t->partitions*(25u+t->len+g->len);return live;}
static const unsigned char *record_key(const StreamRecord*r){return r->data+r->len;}
static void part_link(StreamStore*s,StreamTopic*t,StreamPart*x,StreamRecord*r){if(x->tail)x->tail->next=r;else x->head=r;x->tail=r;x->next++;x->bytes+=record_bytes(r);t->bytes+=record_bytes(r);t->records++;t->revision++;s->live_bytes+=record_live(t,r);}
static int append_memory(StreamStore*s,StreamTopic*t,uint32_t p,uint64_t off,uint64_t at,const void*k,uint16_t kl,const void*d,uint32_t l){if(p>=t->partitions||(l&&!d)||(kl&&!k))return-1;StreamPart*x=&t->parts[p];if(off!=x->next)return-1;StreamRecord*r=malloc(sizeof*r+(size_t)l+kl);if(!r)return-1;r->next=NULL;r->offset=off;r->at_ms=at;r->len=l;r->key_len=kl;if(l)memcpy(r->data,d,l);if(kl)memcpy(r->data+l,k,kl);part_link(s,t,x,r);return 0;}
static void trim_part(StreamStore*s,StreamTopic*t,uint32_t p,uint64_t base){StreamPart*x=&t->parts[p];uint64_t old=x->base;while(x->head&&x->head->offset<base){StreamRecord*r=x->head;x->head=r->next;x->bytes-=record_bytes(r);t->bytes-=record_bytes(r);t->records--;s->live_bytes-=record_live(t,r);free(r);}if(!x->head)x->tail=NULL;if(base>x->base)x->base=base;if(base>x->next)x->next=base;if(x->base!=old)t->revision++;}
/* Retention pass. In-memory trims happen first; persistence then writes ONE
 * trim boundary per affected partition instead of one record per removed
 * record, so evicting N records costs at most one fsync per partition rather
 * than N. Replay applies trims monotonically per partition, so a single
 * final boundary per partition produces exactly the same recovered state as
 * the historical per-record trim records. Retention is a ceiling, not an
 * acknowledgement: a crash before the boundary lands replays slightly more
 * history, and the startup pass (enforce with persist=0) re-trims it. */
static int enforce(StreamStore*s,StreamTopic*t,int persist){uint64_t now=now_ms();uint64_t base[STREAM_PARTITIONS_MAX];uint32_t touched[STREAM_PARTITIONS_MAX],nt=0;memset(base,0,sizeof base);int rc=0;for(uint32_t p=0;p<t->partitions;p++){StreamPart*x=&t->parts[p];if(!t->max_age_ms||!x->head||now-x->head->at_ms<t->max_age_ms)continue;uint64_t b=0;while(x->head&&now-x->head->at_ms>=t->max_age_ms){b=x->head->offset+1;trim_part(s,t,p,b);}if(b){base[p]=b;touched[nt++]=p;}}while(t->max_bytes&&t->bytes>t->max_bytes){uint32_t bp=UINT32_MAX;uint64_t oldest=UINT64_MAX;for(uint32_t p=0;p<t->partitions;p++)if(t->parts[p].head&&t->parts[p].head->at_ms<oldest){oldest=t->parts[p].head->at_ms;bp=p;}if(bp==UINT32_MAX)break;uint64_t b=t->parts[bp].head->offset+1;trim_part(s,t,bp,b);if(!base[bp])touched[nt++]=bp;base[bp]=b;}if(persist)for(uint32_t i=0;i<nt&&!rc;i++){uint32_t p=touched[i];unsigned char b[14+STREAM_NAME_MAX];u16(b,t->len);memcpy(b+2,t->name,t->len);u32(b+2+t->len,p);u64(b+6+t->len,base[p]);rc=log_record(s,S_TRIM,b,14u+t->len);}return rc?-1:0;}
static StreamGroup *group(StreamStore*s,StreamTopic*t,const char*n,uint32_t l,int create){for(StreamGroup*g=t->groups;g;g=g->next)if(g->len==l&&!memcmp(g->name,n,l))return g;if(!create)return NULL;StreamGroup*g=calloc(1,sizeof*g);if(!g)return NULL;g->name=malloc(l);g->offsets=calloc(t->partitions,sizeof* g->offsets);if(!g->name||!g->offsets){free(g->name);free(g->offsets);free(g);return NULL;}memcpy(g->name,n,l);g->len=l;g->next=t->groups;t->groups=g;s->live_bytes+=(uint64_t)t->partitions*(25u+t->len+l);return g;}
static void group_reap_locked(StreamGroup*g,uint64_t now){for(StreamMember**link=&g->members;*link;){StreamMember*m=*link;if(m->deadline_ms>now){link=&m->next;continue;}*link=m->next;free(m);if(g->member_count)g->member_count--;g->generation++;}}
static uint32_t group_owners_locked(StreamGroup*g,uint64_t now,uint64_t *owners){group_reap_locked(g,now);uint32_t n=0;for(StreamMember*m=g->members;m;m=m->next)owners[n++]=m->owner;for(uint32_t i=1;i<n;i++){uint64_t x=owners[i];uint32_t j=i;while(j&&owners[j-1]>x){owners[j]=owners[j-1];j--;}owners[j]=x;}return n;}
static int member_assigned_locked(StreamGroup*g,uint64_t owner,uint32_t partition,uint64_t now){uint64_t owners[STREAM_GROUP_MEMBERS_MAX];uint32_t n=group_owners_locked(g,now,owners);for(uint32_t i=0;i<n;i++)if(owners[i]==owner)return partition%n==i;return 0;}
/* O(1): the live checkpoint-size estimate is maintained incrementally at the
 * shared mutation points (see struct StreamStore), so deciding whether a
 * compaction is due no longer scans every retained record. */
static uint64_t compact_limit(StreamStore*s){uint64_t live=s->live_bytes;return live*2u+65536u>STREAM_COMPACT_FLOOR?live*2u+65536u:STREAM_COMPACT_FLOOR;}
static int compact_record(int fd,unsigned char op,const unsigned char*b,uint32_t n,uint64_t *bytes){if(write_record_fd(fd,op,b,n,0))return-1;*bytes+=9u+n;return 0;}
/* Rebuild a self-contained WAL from the retained records and latest group
 * offsets. The temp file is synced and renamed atomically; an interruption
 * before rename leaves the old valid WAL, and an interruption after rename
 * leaves the new valid WAL. The caller holds s->mu throughout. */
static int stream_compact_locked(StreamStore*s){if(!s->path)return 0;size_t n=strlen(s->path);if(n>PATH_MAX-16)return-1;char tmp[PATH_MAX];snprintf(tmp,sizeof tmp,"%s.compact.XXXXXX",s->path);int fd=mkstemp(tmp);if(fd<0)return-1;uint64_t bytes=0;int rc=0;for(StreamTopic*t=s->topics;t&&!rc;t=t->next){unsigned char*b=malloc(22u+t->len);if(!b){rc=-1;break;}u16(b,t->len);memcpy(b+2,t->name,t->len);u32(b+2+t->len,t->partitions);u64(b+6+t->len,t->max_bytes);u64(b+14+t->len,t->max_age_ms);rc=compact_record(fd,S_DECLARE,b,22u+t->len,&bytes);free(b);if(!rc){/* The checkpoint preserves the topic incarnation and both partition
       * boundaries, including empty partitions whose base/next are nonzero. */
      unsigned char*ident=malloc(18u+t->len);if(!ident)rc=-1;else{u16(ident,t->len);memcpy(ident+2,t->name,t->len);memcpy(ident+2+t->len,t->id,STREAM_ID_LEN);rc=compact_record(fd,S_IDENTITY,ident,18u+t->len,&bytes);free(ident);}}for(uint32_t p=0;p<t->partitions&&!rc;p++){StreamPart*x=&t->parts[p];if(x->base){unsigned char *q=malloc(14u+t->len);if(!q){rc=-1;break;}u16(q,t->len);memcpy(q+2,t->name,t->len);u32(q+2+t->len,p);u64(q+6+t->len,x->base);rc=compact_record(fd,S_TRIM,q,14u+t->len,&bytes);free(q);}for(StreamRecord*r=x->head;r&&!rc;r=r->next){size_t qlen=(r->key_len?28u:26u)+t->len+r->len+r->key_len;unsigned char*q=malloc(qlen);if(!q){rc=-1;break;}u16(q,t->len);memcpy(q+2,t->name,t->len);u32(q+2+t->len,p);u64(q+6+t->len,r->offset);u64(q+14+t->len,r->at_ms);if(r->key_len){u16(q+22+t->len,r->key_len);u32(q+24+t->len,r->len);if(r->len)memcpy(q+28+t->len,r->data,r->len);memcpy(q+28+t->len+r->len,record_key(r),r->key_len);rc=compact_record(fd,S_APPEND_KEY,q,(uint32_t)qlen,&bytes);}else{u32(q+22+t->len,r->len);if(r->len)memcpy(q+26+t->len,r->data,r->len);rc=compact_record(fd,S_APPEND,q,(uint32_t)qlen,&bytes);}free(q);}}for(StreamGroup*g=t->groups;g&&!rc;g=g->next)for(uint32_t p=0;p<t->partitions&&!rc;p++){unsigned char*q=malloc(16u+t->len+g->len);if(!q){rc=-1;break;}u16(q,t->len);memcpy(q+2,t->name,t->len);u16(q+2+t->len,g->len);memcpy(q+4+t->len,g->name,g->len);u32(q+4+t->len+g->len,p);u64(q+8+t->len+g->len,g->offsets[p]);rc=compact_record(fd,S_COMMIT,q,16u+t->len+g->len,&bytes);free(q);}if(!rc){unsigned char*q=malloc(10u+t->len);if(!q){rc=-1;break;}u16(q,t->len);memcpy(q+2,t->name,t->len);u64(q+2+t->len,t->revision);rc=compact_record(fd,S_REVISION,q,10u+t->len,&bytes);free(q);}}
if(!rc&&fsync(fd))rc=-1;
if(close(fd))rc=-1;
if(!rc&&rename(tmp,s->path))rc=-1;
if(!rc&&fsync_parent(s->path))rc=-1;
if(!rc){/* Every mutation holds `mu`, so nothing can have staged a record since
   * the caller entered; drop the buffer rather than let a stray byte land
   * out of order in the freshly published file. */
  s->wal_buf_len=0;close(s->fd);s->fd=open(s->path,O_RDWR|O_NOFOLLOW);off_t end=s->fd<0?-1:lseek(s->fd,0,SEEK_END);
  if(s->fd<0||end<0)rc=-1;else{s->wal_bytes=bytes;s->wal_off=end;}}
if(rc)unlink(tmp);
if(!rc){/* The synced, atomically published checkpoint contains every
   * in-memory record, so all outstanding sequence numbers are durable. */
  s->synced_seq=s->wal_seq;pthread_cond_broadcast(&s->sync_cond);}
return rc;}
static int compact_maybe_locked(StreamStore*s){if(s->fd<0||s->wal_bytes<=compact_limit(s))return 0;/* Let an in-flight fsync of the WAL being replaced finish first. */while(s->syncer&&!s->failed)pthread_cond_wait(&s->sync_cond,&s->mu);if(stream_compact_locked(s)){s->failed=1;return-1;}return 0;}
static uint32_t hash_key(const void*p,uint16_t n){const unsigned char*b=p;uint32_t h=2166136261u;for(uint16_t i=0;i<n;i++)h=(h^b[i])*16777619u;return h;}
static int replay(StreamStore*s,unsigned char op,const unsigned char*b,uint32_t n){if(op==S_DECLARE){if(n<22)return-1;uint16_t l=g16(b);if(n!=22u+l)return-1;return add_topic(s,(const char*)b+2,l,g32(b+2+l),g64(b+6+l),g64(b+14+l));}if(n<2)return-1;uint16_t l=g16(b);if(l>STREAM_NAME_MAX||n<2u+l)return-1;if(op==S_DELETE){if(n!=2u+l)return-1;for(StreamTopic**link=&s->topics;*link;link=&(*link)->next)if((*link)->len==l&&!memcmp((*link)->name,b+2,l)){StreamTopic*gone=*link;uint64_t live=topic_live(gone);*link=gone->next;gone->next=NULL;s->live_bytes=s->live_bytes>=live?s->live_bytes-live:0;free_topic(gone);return 0;}return-1;}StreamTopic*t=topic(s,(const char*)b+2,l);if(!t)return-1;if(op==S_RETENTION){if(n!=18u+l)return-1;t->max_bytes=g64(b+2+l);t->max_age_ms=g64(b+10+l);t->revision++;return 0;}if(op==S_REVISION){if(n!=10u+l||!g64(b+2+l))return-1;t->revision=g64(b+2+l);return 0;}if(op==S_APPEND){if(n<26u+l)return-1;uint32_t p=g32(b+2+l),dl=g32(b+22+l);if(n!=26u+l+dl)return-1;return append_memory(s,t,p,g64(b+6+l),g64(b+14+l),NULL,0,b+26+l,dl);}if(op==S_APPEND_KEY){if(n<28u+l)return-1;uint32_t p=g32(b+2+l),dl=g32(b+24+l);uint16_t kl=g16(b+22+l);if(n!=28u+l+(uint64_t)dl+kl)return-1;return append_memory(s,t,p,g64(b+6+l),g64(b+14+l),b+28+l+dl,kl,b+28+l,dl);}if(op==S_APPEND_BATCH||op==S_APPEND_BATCH_KEY){if(n<6u+l)return-1;uint32_t count=g32(b+2+l);if(!count||count>STREAM_FETCH_MAX)return-1;size_t at=6u+l;for(uint32_t i=0;i<count;i++){size_t header=op==S_APPEND_BATCH_KEY?26u:24u;if(at+header>n)return-1;uint32_t p=g32(b+at),dl=g32(b+at+(op==S_APPEND_BATCH_KEY?22:20));uint16_t kl=op==S_APPEND_BATCH_KEY?g16(b+at+20):0;if(dl>(uint64_t)n-at-header-kl)return-1;if(append_memory(s,t,p,g64(b+at+4),g64(b+at+12),kl?b+at+header+dl:NULL,kl,b+at+header,dl))return-1;at+=header+dl+kl;}return at==n?0:-1;}if(op==S_TRIM){if(n!=14u+l)return-1;uint32_t p=g32(b+2+l);if(p>=t->partitions)return-1;trim_part(s,t,p,g64(b+6+l));return 0;}if(op==S_IDENTITY){if(n!=18u+l)return-1;if(t->id_persisted)memcpy(t->id,b+2+l,STREAM_ID_LEN);else{memcpy(t->id,b+2+l,STREAM_ID_LEN);t->id_persisted=1;s->live_bytes+=identity_live(t);}return 0;}if(op==S_COMMIT){if(n<16u+l)return-1;uint16_t gl=g16(b+2+l);if(n!=16u+l+gl)return-1;uint32_t p=g32(b+4+l+gl);if(p>=t->partitions)return-1;StreamGroup*g=group(s,t,(const char*)b+4+l,gl,1);if(!g)return-1;g->offsets[p]=g64(b+8+l+gl);return 0;}return-1;}
/* A crashed compaction leaves a `.compact.*` sibling behind; the pre-rename
 * WAL was still valid, so the stale temp is safe to delete at startup. The
 * store is single-owner, so no concurrent compaction can be in progress. */
static void remove_stale_temps(const char*path){const char*base=strrchr(path,'/');size_t bl;if(base){base++;bl=strlen(base);}else{base=path;bl=strlen(path);}if(!bl||bl>PATH_MAX-16)return;char prefix[PATH_MAX];memcpy(prefix,base,bl);memcpy(prefix+bl,".compact.",10);size_t dl=(size_t)(base-path);char dir[PATH_MAX];if(dl==0)dir[0]=0;else if(dl==1){dir[0]='/';dir[1]=0;}else{if(dl-1>sizeof dir-1)return;memcpy(dir,path,dl-1);dir[dl-1]=0;}DIR*x=opendir(dl?dir:".");if(!x)return;struct dirent*e;while((e=readdir(x)))if(!strncmp(e->d_name,prefix,bl+9)){char full[PATH_MAX];int n=snprintf(full,sizeof full,"%s%s%s",dl?dir:"",(dl&&dir[0]&&dir[strlen(dir)-1]!='/')?"/":"",e->d_name);if(n>0&&n<(int)sizeof full)unlink(full);}closedir(x);}
StreamStore *stream_store_open(const char*path){StreamStore*s=calloc(1,sizeof*s);if(!s)return NULL;pthread_mutex_init(&s->mu,NULL);pthread_cond_init(&s->sync_cond,NULL);s->fd=-1;if(path){remove_stale_temps(path);s->path=strdup(path);if(!s->path){stream_store_close(s);return NULL;}/* No O_APPEND: writes address wal_off so they can land inside a reservation. */
    s->fd=open(path,O_RDWR|O_CREAT|O_NOFOLLOW,0600);if(s->fd<0||fchmod(s->fd,0600)){stream_store_close(s);return NULL;}struct stat st;if(fstat(s->fd,&st)||!S_ISREG(st.st_mode)){stream_store_close(s);return NULL;}unsigned char h[9];lseek(s->fd,0,SEEK_SET);off_t good=0;for(;;){ssize_t r=read(s->fd,h,9);if(r==0)break;if(r!=9)break;uint32_t n=g32(h+1);if(n>(64u<<20))break;unsigned char*b=malloc(n?n:1);if(!b)break;size_t got=0;while(got<n){r=read(s->fd,b+got,n-got);if(r<=0)break;got+=(size_t)r;}uint32_t c=crc32(h,1)^crc32(b,n);int ok=got==n&&c==g32(h+5)&&replay(s,h[0],b,n)==0;free(b);if(!ok)break;good+=9+n;}if(ftruncate(s->fd,good)){stream_store_close(s);return NULL;}s->wal_bytes=(uint64_t)good;s->wal_off=good;lseek(s->fd,0,SEEK_END);{/* Legacy declarations carry no identity record: assign one and durably
     * persist it before the store is exposed, so a replay of this WAL never
     * regenerates it. An old binary that encounters S_IDENTITY truncates at
     * the break point (see PROTOCOL.md) — in-place downgrade is unsafe. */
      int upgraded=0;for(StreamTopic*t=s->topics;t;t=t->next)if(!t->id_persisted){unsigned char*ident=malloc(18u+t->len);if(!ident){stream_store_close(s);return NULL;}u16(ident,t->len);memcpy(ident+2,t->name,t->len);memcpy(ident+2+t->len,t->id,STREAM_ID_LEN);int wr=log_record(s,S_IDENTITY,ident,18u+t->len);free(ident);if(wr){stream_store_close(s);return NULL;}t->id_persisted=1;s->live_bytes+=identity_live(t);upgraded=1;}if(upgraded){if(wal_flush_locked(s)||fsync(s->fd)){stream_store_close(s);return NULL;}s->synced_seq=s->wal_seq;s->wal_bytes=(uint64_t)s->wal_off;}}for(StreamTopic*t=s->topics;t;t=t->next)if(enforce(s,t,0)){stream_store_close(s);return NULL;}}return s;}
void stream_store_close(StreamStore*s){if(!s)return;pthread_mutex_lock(&s->mu);s->failed=1;pthread_cond_broadcast(&s->sync_cond);pthread_mutex_unlock(&s->mu);
  if(s->fd>=0)close(s->fd);
  free(s->wal_buf);free(s->path);free_topic(s->topics);pthread_mutex_destroy(&s->mu);pthread_cond_destroy(&s->sync_cond);free(s);}
/* A new declaration assigns and durably persists the topic identity before
 * the response, so replay never generates a different one. */
int stream_declare(StreamStore*s,const char*n,uint32_t l,uint32_t p,uint64_t maxb,uint64_t age){if(!s)return-1;pthread_mutex_lock(&s->mu);if(s->failed||s->fd<0||compact_maybe_locked(s)){pthread_mutex_unlock(&s->mu);return-1;}int exists=topic(s,n,l)!=NULL;int rc=add_topic(s,n,l,p,maxb,age);if(rc){pthread_mutex_unlock(&s->mu);return rc;}if(!exists){StreamTopic*t=topic(s,n,l);unsigned char*b=malloc(22+l);unsigned char*ident=malloc(18u+l);if(!b||!ident){free(b);free(ident);pthread_mutex_unlock(&s->mu);return-1;}u16(b,l);memcpy(b+2,n,l);u32(b+2+l,p);u64(b+6+l,maxb);u64(b+14+l,age);int wr=log_record(s,S_DECLARE,b,22+l);free(b);if(!wr){u16(ident,l);memcpy(ident+2,n,l);memcpy(ident+2+l,t->id,STREAM_ID_LEN);wr=log_record(s,S_IDENTITY,ident,18u+l);}free(ident);if(wr){pthread_mutex_unlock(&s->mu);return-1;}t->id_persisted=1;s->live_bytes+=identity_live(t);rc=stream_wait_durable_locked(s,s->wal_seq);if(rc){pthread_mutex_unlock(&s->mu);return rc;}}pthread_mutex_unlock(&s->mu);return 0;}
int stream_append(StreamStore*s,const char*n,uint32_t l,uint32_t hint,const void*k,uint16_t kl,const void*d,uint32_t dl,uint64_t*op,uint64_t*oo){if(!s||dl>(64u<<20)||(dl&&!d)||(kl&&!k)||dl>(64u<<20)-26u-l-(kl?2u+kl:0u))return-1;pthread_mutex_lock(&s->mu);if(s->failed||compact_maybe_locked(s)){pthread_mutex_unlock(&s->mu);return-1;}StreamTopic*t=topic(s,n,l);if(!t){pthread_mutex_unlock(&s->mu);return-1;}uint32_t p=hint==UINT32_MAX?(kl?hash_key(k,kl)%t->partitions:0):hint;if(p>=t->partitions){pthread_mutex_unlock(&s->mu);return-1;}uint64_t off=t->parts[p].next,at=now_ms();size_t bytes=(kl?28u:26u)+l+dl+kl;unsigned char*b=malloc(bytes);if(!b){pthread_mutex_unlock(&s->mu);return-1;}u16(b,l);memcpy(b+2,n,l);u32(b+2+l,p);u64(b+6+l,off);u64(b+14+l,at);if(kl){u16(b+22+l,kl);u32(b+24+l,dl);if(dl)memcpy(b+28+l,d,dl);memcpy(b+28+l+dl,k,kl);}else{u32(b+22+l,dl);if(dl)memcpy(b+26+l,d,dl);}int rc=log_record(s,kl?S_APPEND_KEY:S_APPEND,b,(uint32_t)bytes);free(b);if(!rc)rc=append_memory(s,t,p,off,at,k,kl,d,dl);if(!rc)rc=enforce(s,t,1);if(!rc){rc=stream_wait_durable_locked(s,s->wal_seq);if(op)*op=p;if(oo)*oo=off;}pthread_mutex_unlock(&s->mu);return rc;}
int stream_append_batch(StreamStore*s,const char*n,uint32_t l,uint32_t hint,const StreamAppendInput*in,uint32_t count,StreamAppendResult*out){if(!s||!in||!out||!count||count>STREAM_FETCH_MAX)return-1;pthread_mutex_lock(&s->mu);if(s->failed||compact_maybe_locked(s)){pthread_mutex_unlock(&s->mu);return-1;}StreamTopic*t=topic(s,n,l);if(!t){pthread_mutex_unlock(&s->mu);return-1;}uint32_t*parts=calloc(count,sizeof*parts);StreamRecord**records=calloc(count,sizeof*records);unsigned char*b=NULL;if(!parts||!records){free(parts);free(records);pthread_mutex_unlock(&s->mu);return-1;}size_t bytes=6u+l;int keyed=0;uint64_t next[STREAM_PARTITIONS_MAX];for(uint32_t p=0;p<t->partitions;p++)next[p]=t->parts[p].next;uint64_t at=now_ms();int rc=-1;for(uint32_t i=0;i<count;i++){size_t item=24u+(size_t)in[i].len+in[i].key_len;if((in[i].len&&!in[i].data)||(in[i].key_len&&!in[i].key)||item>(64u<<20)-bytes)goto done;uint32_t p=hint==UINT32_MAX?(in[i].key_len?hash_key(in[i].key,in[i].key_len)%t->partitions:0):hint;if(p>=t->partitions)goto done;parts[i]=p;out[i].partition=p;out[i].offset=next[p]++;records[i]=malloc(sizeof*records[i]+in[i].len+in[i].key_len);if(!records[i])goto done;records[i]->next=NULL;records[i]->offset=out[i].offset;records[i]->at_ms=at;records[i]->len=in[i].len;records[i]->key_len=in[i].key_len;if(in[i].len)memcpy(records[i]->data,in[i].data,in[i].len);if(in[i].key_len){memcpy(records[i]->data+in[i].len,in[i].key,in[i].key_len);keyed=1;}bytes+=item;}if(keyed){if(bytes>(64u<<20)-2u*count)goto done;bytes+=2u*count;}b=malloc(bytes);if(!b)goto done;u16(b,l);memcpy(b+2,n,l);u32(b+2+l,count);size_t pos=6u+l;for(uint32_t i=0;i<count;i++){size_t header=keyed?26u:24u;u32(b+pos,parts[i]);u64(b+pos+4,out[i].offset);u64(b+pos+12,at);if(keyed){u16(b+pos+20,records[i]->key_len);u32(b+pos+22,records[i]->len);if(records[i]->len)memcpy(b+pos+26,records[i]->data,records[i]->len);if(records[i]->key_len)memcpy(b+pos+26+records[i]->len,record_key(records[i]),records[i]->key_len);}else{u32(b+pos+20,records[i]->len);if(records[i]->len)memcpy(b+pos+24,records[i]->data,records[i]->len);}pos+=header+records[i]->len+(keyed?records[i]->key_len:0);}if(log_record(s,keyed?S_APPEND_BATCH_KEY:S_APPEND_BATCH,b,(uint32_t)bytes))goto done;for(uint32_t i=0;i<count;i++){part_link(s,t,&t->parts[parts[i]],records[i]);records[i]=NULL;}rc=enforce(s,t,1);if(!rc)rc=stream_wait_durable_locked(s,s->wal_seq);done:free(b);for(uint32_t i=0;i<count;i++)free(records[i]);free(records);free(parts);pthread_mutex_unlock(&s->mu);return rc;}
int stream_fetch(StreamStore*s,const char*n,uint32_t l,uint32_t p,uint64_t off,uint32_t max,uint64_t max_bytes,StreamRecordView**out,uint32_t*count){if(!s||!out||!count||!max||max>STREAM_FETCH_MAX||max_bytes<16)return-1;*out=NULL;*count=0;pthread_mutex_lock(&s->mu);StreamTopic*t=topic(s,n,l);if(!t||p>=t->partitions){pthread_mutex_unlock(&s->mu);return 0;}StreamPart*x=&t->parts[p];uint32_t c=0;uint64_t bytes=4;for(StreamRecord*r=x->head;r&&c<max;r=r->next)if(r->offset>=off){uint64_t need=14u+r->len+r->key_len;if(need>max_bytes-bytes){if(!c){pthread_mutex_unlock(&s->mu);return-2;}break;}bytes+=need;c++;}StreamRecordView*v=calloc(c?c:1,sizeof*v);if(!v){pthread_mutex_unlock(&s->mu);return-1;}uint32_t i=0;for(StreamRecord*r=x->head;r&&i<c;r=r->next)if(r->offset>=off){v[i].offset=r->offset;v[i].key_len=r->key_len;v[i].len=r->len;v[i].data=malloc(r->len?r->len:1);v[i].key=r->key_len?malloc(r->key_len):NULL;if(!v[i].data||(r->key_len&&!v[i].key)){stream_fetch_free(v,i+1);pthread_mutex_unlock(&s->mu);return-1;}if(r->len)memcpy((void*)v[i].data,r->data,r->len);if(r->key_len)memcpy((void*)v[i].key,record_key(r),r->key_len);i++;}pthread_mutex_unlock(&s->mu);*out=v;*count=c;return 1;}
void stream_fetch_free(StreamRecordView*v,uint32_t n){if(v){for(uint32_t i=0;i<n;i++){free((void*)v[i].data);free((void*)v[i].key);}free(v);}}
/* One snapshot: apply retention through its existing durability machinery,
 * then read identity, boundaries, range decision, and copied records under
 * the same lock hold, so retention or recreation cannot split them. */
int stream_fetch_metadata(StreamStore*s,const char*n,uint32_t l,uint32_t p,uint64_t off,uint32_t max,uint64_t max_bytes,const unsigned char*expected_id,unsigned char*out_id,uint64_t*out_base,uint64_t*out_next,uint64_t*out_resume,StreamFetchRange*out_range,StreamRecordView**out,uint32_t*out_count){if(!s||!n||!l||!out_id||!out_base||!out_next||!out_resume||!out_range||!out||!out_count||!max||max>STREAM_FETCH_MAX||max_bytes<16)return-1;*out=NULL;*out_count=0;pthread_mutex_lock(&s->mu);StreamTopic*t=topic(s,n,l);if(!t||p>=t->partitions){pthread_mutex_unlock(&s->mu);return 3;}if(enforce(s,t,1)){pthread_mutex_unlock(&s->mu);return-1;}StreamPart*x=&t->parts[p];memcpy(out_id,t->id,STREAM_ID_LEN);*out_base=x->base;*out_next=x->next;StreamFetchRange range=STREAM_RANGE_OK;if(expected_id&&memcmp(expected_id,t->id,STREAM_ID_LEN))range=STREAM_RANGE_RECREATED;else if(off<x->base)range=STREAM_RANGE_EXPIRED;else if(off>x->next)range=STREAM_RANGE_AHEAD;if(range!=STREAM_RANGE_OK){*out_range=range;*out_resume=off;pthread_mutex_unlock(&s->mu);return 1;}uint32_t c=0;uint64_t bytes=4;for(StreamRecord*r=x->head;r&&c<max;r=r->next)if(r->offset>=off){uint64_t need=14u+r->len+r->key_len;if(need>max_bytes-bytes){if(!c){pthread_mutex_unlock(&s->mu);return-2;}break;}bytes+=need;c++;}StreamRecordView*v=calloc(c?c:1,sizeof*v);if(!v){pthread_mutex_unlock(&s->mu);return-1;}uint32_t i=0;uint64_t resume=off;for(StreamRecord*r=x->head;r&&i<c;r=r->next)if(r->offset>=off){v[i].offset=r->offset;v[i].key_len=r->key_len;v[i].len=r->len;v[i].data=malloc(r->len?r->len:1);v[i].key=r->key_len?malloc(r->key_len):NULL;if(!v[i].data||(r->key_len&&!v[i].key)){stream_fetch_free(v,i+1);pthread_mutex_unlock(&s->mu);return-1;}if(r->len)memcpy((void*)v[i].data,r->data,r->len);if(r->key_len)memcpy((void*)v[i].key,record_key(r),r->key_len);resume=r->offset==UINT64_MAX?UINT64_MAX:r->offset+1;i++;}pthread_mutex_unlock(&s->mu);*out=v;*out_count=i;*out_resume=resume;*out_range=STREAM_RANGE_OK;return 1;}
int stream_revision(StreamStore*s,const char*n,uint32_t l,uint64_t*out){if(!s||!out)return-1;pthread_mutex_lock(&s->mu);StreamTopic*t=topic(s,n,l);if(!t){pthread_mutex_unlock(&s->mu);return 0;}*out=t->revision;pthread_mutex_unlock(&s->mu);return 1;}
int stream_config_snapshot(StreamStore*s,const char*n,uint32_t l,uint32_t*out_parts,uint64_t*out_max_bytes,uint64_t*out_max_age,uint64_t*out_revision){if(!s||!out_parts||!out_max_bytes||!out_max_age||!out_revision)return-1;pthread_mutex_lock(&s->mu);StreamTopic*t=topic(s,n,l);if(!t){pthread_mutex_unlock(&s->mu);return 0;}*out_parts=t->partitions;*out_max_bytes=t->max_bytes;*out_max_age=t->max_age_ms;*out_revision=t->revision;pthread_mutex_unlock(&s->mu);return 1;}
int stream_partition_snapshot(StreamStore*s,const char*n,uint32_t l,StreamPartitionStats*out,uint32_t cap,uint32_t*count,uint64_t*revision){if(!s||!out||!count)return-1;pthread_mutex_lock(&s->mu);StreamTopic*t=topic(s,n,l);if(!t){pthread_mutex_unlock(&s->mu);return 0;}if(cap<t->partitions){pthread_mutex_unlock(&s->mu);return-1;}for(uint32_t p=0;p<t->partitions;p++){out[p].base_offset=t->parts[p].base;out[p].next_offset=t->parts[p].next;out[p].retained_bytes=t->parts[p].bytes;}*count=t->partitions;if(revision)*revision=t->revision;pthread_mutex_unlock(&s->mu);return 1;}
int stream_truncate_if_revision(StreamStore*s,const char*n,uint32_t l,uint32_t p,uint64_t base,uint64_t expected){if(!s)return-1;pthread_mutex_lock(&s->mu);if(s->failed||compact_maybe_locked(s)){pthread_mutex_unlock(&s->mu);return-1;}StreamTopic*t=topic(s,n,l);if(!t||p>=t->partitions){pthread_mutex_unlock(&s->mu);return 3;}StreamPart*x=&t->parts[p];if(t->revision!=expected){pthread_mutex_unlock(&s->mu);return 1;}if(base<x->base||base>x->next){pthread_mutex_unlock(&s->mu);return 2;}unsigned char*b=malloc(14u+l);if(!b){pthread_mutex_unlock(&s->mu);return-1;}u16(b,l);memcpy(b+2,n,l);u32(b+2+l,p);u64(b+6+l,base);int rc=log_record(s,S_TRIM,b,14u+l);free(b);if(!rc){trim_part(s,t,p,base);rc=stream_wait_durable_locked(s,s->wal_seq);}pthread_mutex_unlock(&s->mu);return rc;}
int stream_set_retention_if_revision(StreamStore*s,const char*n,uint32_t l,uint64_t maxb,uint64_t age,uint64_t expected){if(!s||!n||!l||l>STREAM_NAME_MAX)return-1;pthread_mutex_lock(&s->mu);if(s->failed||s->fd<0||compact_maybe_locked(s)){pthread_mutex_unlock(&s->mu);return-1;}StreamTopic*t=topic(s,n,l);if(!t){pthread_mutex_unlock(&s->mu);return 3;}if(t->revision!=expected){pthread_mutex_unlock(&s->mu);return 1;}unsigned char*b=malloc(18u+l);if(!b){pthread_mutex_unlock(&s->mu);return-1;}u16(b,l);memcpy(b+2,n,l);u64(b+2+l,maxb);u64(b+10+l,age);int rc=log_record(s,S_RETENTION,b,18u+l);free(b);if(!rc){t->max_bytes=maxb;t->max_age_ms=age;t->revision++;rc=enforce(s,t,1);if(!rc)rc=stream_wait_durable_locked(s,s->wal_seq);}pthread_mutex_unlock(&s->mu);return rc;}
int stream_delete_if_revision(StreamStore*s,const char*n,uint32_t l,uint64_t expected){if(!s||!n||!l||l>STREAM_NAME_MAX)return-1;pthread_mutex_lock(&s->mu);if(s->failed||s->fd<0||compact_maybe_locked(s)){pthread_mutex_unlock(&s->mu);return-1;}StreamTopic**link=&s->topics;while(*link&&((*link)->len!=l||memcmp((*link)->name,n,l)))link=&(*link)->next;StreamTopic*t=*link;if(!t){pthread_mutex_unlock(&s->mu);return 3;}if(t->revision!=expected){pthread_mutex_unlock(&s->mu);return 1;}unsigned char b[2+STREAM_NAME_MAX];u16(b,l);memcpy(b+2,n,l);if(log_record(s,S_DELETE,b,2u+l)){pthread_mutex_unlock(&s->mu);return-1;}if(stream_wait_durable_locked(s,s->wal_seq)){pthread_mutex_unlock(&s->mu);return-1;}uint64_t live=topic_live(t);*link=t->next;t->next=NULL;s->live_bytes=s->live_bytes>=live?s->live_bytes-live:0;free_topic(t);pthread_mutex_unlock(&s->mu);return 0;}
int stream_commit(StreamStore*s,const char*n,uint32_t l,const char*g,uint32_t gl,uint32_t p,uint64_t off){if(!s||!gl||gl>STREAM_GROUP_MAX)return-1;pthread_mutex_lock(&s->mu);if(s->failed||compact_maybe_locked(s)){pthread_mutex_unlock(&s->mu);return-1;}StreamTopic*t=topic(s,n,l);if(!t||p>=t->partitions||off<t->parts[p].base||off>t->parts[p].next){pthread_mutex_unlock(&s->mu);return-1;}StreamGroup*x=group(s,t,g,gl,1);if(!x){pthread_mutex_unlock(&s->mu);return-1;}/* A delayed acknowledgement must never rewind a later durable commit.  The
 * explicit reset operation is the only supported way to move an offset back. */
if(off<=x->offsets[p]){pthread_mutex_unlock(&s->mu);return 0;}unsigned char*b=malloc(16+l+gl);if(!b){pthread_mutex_unlock(&s->mu);return-1;}u16(b,l);memcpy(b+2,n,l);u16(b+2+l,gl);memcpy(b+4+l,g,gl);u32(b+4+l+gl,p);u64(b+8+l+gl,off);int rc=log_record(s,S_COMMIT,b,16+l+gl);free(b);if(!rc){x->offsets[p]=off;rc=stream_wait_durable_locked(s,s->wal_seq);}pthread_mutex_unlock(&s->mu);return rc;}
int stream_group_generation(StreamStore*s,const char*n,uint32_t l,const char*g,uint32_t gl,uint64_t*out){if(!s||!g||!gl||gl>STREAM_GROUP_MAX||!out)return-1;pthread_mutex_lock(&s->mu);StreamTopic*t=topic(s,n,l);StreamGroup*x=t?group(s,t,g,gl,0):NULL;if(!x){pthread_mutex_unlock(&s->mu);return 0;}group_reap_locked(x,mono_ms());*out=x->generation;pthread_mutex_unlock(&s->mu);return 1;}
int stream_commit_if_generation(StreamStore*s,const char*n,uint32_t l,const char*g,uint32_t gl,uint32_t p,uint64_t off,uint64_t expected){if(!s||!g||!gl||gl>STREAM_GROUP_MAX)return-1;pthread_mutex_lock(&s->mu);if(s->failed||compact_maybe_locked(s)){pthread_mutex_unlock(&s->mu);return-1;}StreamTopic*t=topic(s,n,l);StreamGroup*x=t?group(s,t,g,gl,0):NULL;if(!t||!x||p>=t->partitions){pthread_mutex_unlock(&s->mu);return 3;}group_reap_locked(x,mono_ms());if(x->generation!=expected){pthread_mutex_unlock(&s->mu);return 1;}if(off<t->parts[p].base||off>t->parts[p].next){pthread_mutex_unlock(&s->mu);return 2;}unsigned char*b=malloc(16+l+gl);if(!b){pthread_mutex_unlock(&s->mu);return-1;}u16(b,l);memcpy(b+2,n,l);u16(b+2+l,gl);memcpy(b+4+l,g,gl);u32(b+4+l+gl,p);u64(b+8+l+gl,off);int rc=log_record(s,S_COMMIT,b,16+l+gl);free(b);if(!rc){x->offsets[p]=off;rc=stream_wait_durable_locked(s,s->wal_seq);}pthread_mutex_unlock(&s->mu);return rc;}
int stream_commit_batch_if_generation(StreamStore*s,const char*n,uint32_t l,const char*g,uint32_t gl,const StreamCommitInput*in,uint32_t count,uint64_t expected){if(!s||!g||!gl||gl>STREAM_GROUP_MAX||!in||!count||count>STREAM_FETCH_MAX)return-1;pthread_mutex_lock(&s->mu);if(s->failed||compact_maybe_locked(s)){pthread_mutex_unlock(&s->mu);return-1;}StreamTopic*t=topic(s,n,l);StreamGroup*x=t?group(s,t,g,gl,0):NULL;if(!t||!x){pthread_mutex_unlock(&s->mu);return 3;}group_reap_locked(x,mono_ms());if(x->generation!=expected){pthread_mutex_unlock(&s->mu);return 1;}for(uint32_t i=0;i<count;i++)if(in[i].partition>=t->partitions){pthread_mutex_unlock(&s->mu);return 3;}else if(in[i].offset<t->parts[in[i].partition].base||in[i].offset>t->parts[in[i].partition].next){pthread_mutex_unlock(&s->mu);return 2;}size_t record=16u+l+gl;if(record>UINT32_MAX/count){pthread_mutex_unlock(&s->mu);return-1;}unsigned char*b=malloc(record*count);if(!b){pthread_mutex_unlock(&s->mu);return-1;}size_t pos=0;for(uint32_t i=0;i<count;i++){u16(b+pos,l);memcpy(b+pos+2,n,l);u16(b+pos+2+l,gl);memcpy(b+pos+4+l,g,gl);u32(b+pos+4+l+gl,in[i].partition);u64(b+pos+8+l+gl,in[i].offset);pos+=record;}int rc=0;pos=0;for(uint32_t i=0;i<count&&!rc;i++){rc=log_record(s,S_COMMIT,b+pos,(uint32_t)record);pos+=record;}free(b);if(!rc){for(uint32_t i=0;i<count;i++)x->offsets[in[i].partition]=in[i].offset;rc=stream_wait_durable_locked(s,s->wal_seq);}pthread_mutex_unlock(&s->mu);return rc;}
int stream_group_reset_offsets_if_generation(StreamStore*s,const char*n,uint32_t l,const char*g,uint32_t gl,uint64_t expected,StreamOffsetResetStrategy strategy,uint64_t absolute,int64_t delta,int force,uint64_t*old,uint64_t*next,uint32_t cap,uint32_t*out_count){if(!s||!g||!gl||gl>STREAM_GROUP_MAX||strategy>STREAM_OFFSET_RESET_RELATIVE)return-1;if(out_count)*out_count=0;pthread_mutex_lock(&s->mu);if(s->failed||compact_maybe_locked(s)){pthread_mutex_unlock(&s->mu);return-1;}StreamTopic*t=topic(s,n,l);StreamGroup*x=t?group(s,t,g,gl,0):NULL;if(!t||!x){pthread_mutex_unlock(&s->mu);return 3;}if((old||next)&&cap<t->partitions){pthread_mutex_unlock(&s->mu);return-1;}group_reap_locked(x,mono_ms());if(x->generation!=expected){pthread_mutex_unlock(&s->mu);return 1;}if(x->member_count&&!force){pthread_mutex_unlock(&s->mu);return 4;}uint64_t targets[STREAM_PARTITIONS_MAX];for(uint32_t p=0;p<t->partitions;p++){uint64_t value=0,current=x->offsets[p];if(strategy==STREAM_OFFSET_RESET_EARLIEST)value=t->parts[p].base;else if(strategy==STREAM_OFFSET_RESET_LATEST)value=t->parts[p].next;else if(strategy==STREAM_OFFSET_RESET_ABSOLUTE)value=absolute;else if(delta<0){uint64_t amount=(uint64_t)(-(delta+1))+1u;if(amount>current){pthread_mutex_unlock(&s->mu);return 2;}value=current-amount;}else{uint64_t amount=(uint64_t)delta;if(amount>UINT64_MAX-current){pthread_mutex_unlock(&s->mu);return 2;}value=current+amount;}if(value<t->parts[p].base||value>t->parts[p].next){pthread_mutex_unlock(&s->mu);return 2;}targets[p]=value;if(old)old[p]=current;if(next)next[p]=value;}size_t record=16u+l+gl;if(record>UINT32_MAX/t->partitions){pthread_mutex_unlock(&s->mu);return-1;}unsigned char*b=malloc(record*t->partitions);if(!b){pthread_mutex_unlock(&s->mu);return-1;}size_t pos=0;for(uint32_t p=0;p<t->partitions;p++){u16(b+pos,l);memcpy(b+pos+2,n,l);u16(b+pos+2+l,gl);memcpy(b+pos+4+l,g,gl);u32(b+pos+4+l+gl,p);u64(b+pos+8+l+gl,targets[p]);pos+=record;}int rc=0;pos=0;for(uint32_t p=0;p<t->partitions&&!rc;p++){rc=log_record(s,S_COMMIT,b+pos,(uint32_t)record);pos+=record;}free(b);if(!rc){for(uint32_t p=0;p<t->partitions;p++)x->offsets[p]=targets[p];rc=stream_wait_durable_locked(s,s->wal_seq);if(!rc&&out_count)*out_count=t->partitions;}pthread_mutex_unlock(&s->mu);return rc;}
int stream_group_join(StreamStore*s,const char*n,uint32_t l,const char*g,uint32_t gl,uint64_t owner,uint32_t lease,uint32_t**out,uint32_t*count,uint64_t*out_generation){if(!s||!g||!gl||gl>STREAM_GROUP_MAX||!owner||!out||!count||!lease||lease>60000)return-1;*out=NULL;*count=0;if(out_generation)*out_generation=0;pthread_mutex_lock(&s->mu);StreamTopic*t=topic(s,n,l);if(!t){pthread_mutex_unlock(&s->mu);return-1;}StreamGroup*x=group(s,t,g,gl,1);if(!x){pthread_mutex_unlock(&s->mu);return-1;}uint64_t now=mono_ms();group_reap_locked(x,now);StreamMember*m=x->members;while(m&&m->owner!=owner)m=m->next;if(!m){if(x->member_count>=STREAM_GROUP_MEMBERS_MAX){pthread_mutex_unlock(&s->mu);return-1;}m=calloc(1,sizeof*m);if(!m){pthread_mutex_unlock(&s->mu);return-1;}m->owner=owner;m->next=x->members;x->members=m;x->member_count++;x->generation++;}m->deadline_ms=now+lease;uint64_t owners[STREAM_GROUP_MEMBERS_MAX];uint32_t members=group_owners_locked(x,now,owners),assigned=0;for(uint32_t p=0;p<t->partitions;p++)if(owners[p%members]==owner)assigned++;uint32_t*parts=calloc(assigned?assigned:1,sizeof*parts);if(!parts){pthread_mutex_unlock(&s->mu);return-1;}uint32_t at=0;for(uint32_t p=0;p<t->partitions;p++)if(owners[p%members]==owner)parts[at++]=p;pthread_mutex_unlock(&s->mu);*out=parts;*count=assigned;if(out_generation)*out_generation=x->generation;return 0;}
int stream_group_leave_member(StreamStore*s,const char*n,uint32_t l,const char*g,uint32_t gl,uint64_t owner){if(!s||!g||!gl||gl>STREAM_GROUP_MAX||!owner)return-1;pthread_mutex_lock(&s->mu);StreamTopic*t=topic(s,n,l);StreamGroup*x=t?group(s,t,g,gl,0):NULL;int removed=0;if(x)for(StreamMember**link=&x->members;*link;){StreamMember*m=*link;if(m->owner!=owner){link=&m->next;continue;}*link=m->next;free(m);if(x->member_count)x->member_count--;x->generation++;removed=1;break;}pthread_mutex_unlock(&s->mu);return removed?0:-1;}
void stream_group_leave_owner(StreamStore*s,uint64_t owner){if(!s||!owner)return;pthread_mutex_lock(&s->mu);for(StreamTopic*t=s->topics;t;t=t->next)for(StreamGroup*g=t->groups;g;g=g->next)for(StreamMember**link=&g->members;*link;){StreamMember*m=*link;if(m->owner!=owner){link=&m->next;continue;}*link=m->next;free(m);if(g->member_count)g->member_count--;g->generation++;}pthread_mutex_unlock(&s->mu);}
void stream_reap(StreamStore*s){if(!s)return;pthread_mutex_lock(&s->mu);uint64_t now=mono_ms();for(StreamTopic*t=s->topics;t;t=t->next)for(StreamGroup*g=t->groups;g;g=g->next)group_reap_locked(g,now);pthread_mutex_unlock(&s->mu);}
int stream_group_member_assigned(StreamStore*s,const char*n,uint32_t l,const char*g,uint32_t gl,uint64_t owner,uint32_t p,uint64_t*out_generation){if(!s||!g||!gl||gl>STREAM_GROUP_MAX||!owner)return-1;pthread_mutex_lock(&s->mu);StreamTopic*t=topic(s,n,l);StreamGroup*x=t?group(s,t,g,gl,0):NULL;if(!t||!x||p>=t->partitions){pthread_mutex_unlock(&s->mu);return 0;}uint64_t now=mono_ms();int assigned=member_assigned_locked(x,owner,p,now);if(out_generation)*out_generation=x->generation;pthread_mutex_unlock(&s->mu);return assigned?1:0;}
int stream_commit_for_owner(StreamStore*s,const char*n,uint32_t l,const char*g,uint32_t gl,uint32_t p,uint64_t off,uint64_t owner){if(!s||!g||!gl||gl>STREAM_GROUP_MAX||!owner)return-1;pthread_mutex_lock(&s->mu);if(s->failed||compact_maybe_locked(s)){pthread_mutex_unlock(&s->mu);return-1;}StreamTopic*t=topic(s,n,l);StreamGroup*x=t?group(s,t,g,gl,0):NULL;if(!t||!x||p>=t->partitions||!member_assigned_locked(x,owner,p,mono_ms())){pthread_mutex_unlock(&s->mu);return-1;}unsigned char*b=malloc(16+l+gl);if(!b){pthread_mutex_unlock(&s->mu);return-1;}u16(b,l);memcpy(b+2,n,l);u16(b+2+l,gl);memcpy(b+4+l,g,gl);u32(b+4+l+gl,p);u64(b+8+l+gl,off);int rc=log_record(s,S_COMMIT,b,16+l+gl);free(b);if(!rc){x->offsets[p]=off;rc=stream_wait_durable_locked(s,s->wal_seq);}pthread_mutex_unlock(&s->mu);return rc;}
int stream_commit_for_owner_if_generation(StreamStore*s,const char*n,uint32_t l,const char*g,uint32_t gl,uint32_t p,uint64_t off,uint64_t owner,uint64_t expected){if(!s||!g||!gl||gl>STREAM_GROUP_MAX||!owner)return-1;pthread_mutex_lock(&s->mu);if(s->failed||compact_maybe_locked(s)){pthread_mutex_unlock(&s->mu);return-1;}StreamTopic*t=topic(s,n,l);StreamGroup*x=t?group(s,t,g,gl,0):NULL;if(!t||!x||p>=t->partitions){pthread_mutex_unlock(&s->mu);return 3;}uint64_t now=mono_ms();if(!member_assigned_locked(x,owner,p,now)){pthread_mutex_unlock(&s->mu);return 3;}if(x->generation!=expected){pthread_mutex_unlock(&s->mu);return 1;}if(off<t->parts[p].base||off>t->parts[p].next){pthread_mutex_unlock(&s->mu);return 2;}unsigned char*b=malloc(16+l+gl);if(!b){pthread_mutex_unlock(&s->mu);return-1;}u16(b,l);memcpy(b+2,n,l);u16(b+2+l,gl);memcpy(b+4+l,g,gl);u32(b+4+l+gl,p);u64(b+8+l+gl,off);int rc=log_record(s,S_COMMIT,b,16+l+gl);free(b);if(!rc){x->offsets[p]=off;rc=stream_wait_durable_locked(s,s->wal_seq);}pthread_mutex_unlock(&s->mu);return rc;}
/* Batch offset commit: one lock hold, one durability wait for the whole
 * batch. Entries apply in order, so a later entry for the same partition
 * overwrites an earlier one, matching sequential single commits. */
int stream_commit_batch_for_owner(StreamStore*s,const char*n,uint32_t l,const char*g,uint32_t gl,uint64_t owner,const StreamCommitInput*in,uint32_t count){if(!s||!g||!gl||gl>STREAM_GROUP_MAX||!count||!in)return-1;pthread_mutex_lock(&s->mu);if(s->failed||compact_maybe_locked(s)){pthread_mutex_unlock(&s->mu);return-1;}StreamTopic*t=topic(s,n,l);if(!t){pthread_mutex_unlock(&s->mu);return-1;}StreamGroup*x=group(s,t,g,gl,owner==0?1:0);if(!x){pthread_mutex_unlock(&s->mu);return-1;}uint64_t now=mono_ms();for(uint32_t i=0;i<count;i++){if(in[i].partition>=t->partitions){pthread_mutex_unlock(&s->mu);return-1;}if(owner&&!member_assigned_locked(x,owner,in[i].partition,now)){pthread_mutex_unlock(&s->mu);return-1;}}unsigned char*b=malloc((16u+l+gl)*count);if(!b){pthread_mutex_unlock(&s->mu);return-1;}size_t pos=0;for(uint32_t i=0;i<count;i++){u16(b+pos,l);memcpy(b+pos+2,n,l);u16(b+pos+2+l,gl);memcpy(b+pos+4+l,g,gl);u32(b+pos+4+l+gl,in[i].partition);u64(b+pos+8+l+gl,in[i].offset);pos+=16u+l+gl;}int rc=0;pos=0;for(uint32_t i=0;i<count&&!rc;i++){rc=log_record(s,S_COMMIT,b+pos,16u+l+gl);pos+=16u+l+gl;}free(b);if(!rc){for(uint32_t i=0;i<count;i++)x->offsets[in[i].partition]=in[i].offset;rc=stream_wait_durable_locked(s,s->wal_seq);}pthread_mutex_unlock(&s->mu);return rc;}
int stream_group_offset(StreamStore*s,const char*n,uint32_t l,const char*g,uint32_t gl,uint32_t p,uint64_t*out){if(!s||!out)return-1;pthread_mutex_lock(&s->mu);StreamTopic*t=topic(s,n,l);StreamGroup*x=t?group(s,t,g,gl,0):NULL;if(!x||p>=t->partitions){pthread_mutex_unlock(&s->mu);return 0;}*out=x->offsets[p];pthread_mutex_unlock(&s->mu);return 1;}
int stream_group_lag(StreamStore*s,const char*n,uint32_t l,const char*g,uint32_t gl,uint32_t p,uint64_t*out){if(!s||!out)return-1;pthread_mutex_lock(&s->mu);StreamTopic*t=topic(s,n,l);StreamGroup*x=t?group(s,t,g,gl,0):NULL;if(!x||p>=t->partitions){pthread_mutex_unlock(&s->mu);return 0;}uint64_t end=t->parts[p].next,offset=x->offsets[p];*out=end>offset?end-offset:0;pthread_mutex_unlock(&s->mu);return 1;}
uint64_t stream_topic_count(StreamStore*s){uint64_t n=0;pthread_mutex_lock(&s->mu);for(StreamTopic*t=s->topics;t;t=t->next)n++;pthread_mutex_unlock(&s->mu);return n;}
void stream_foreach_stats(StreamStore*s,StreamTopicStatsFn fn,void*ud){if(!s||!fn)return;pthread_mutex_lock(&s->mu);for(StreamTopic*t=s->topics;t;t=t->next)fn(t->name,t->len,t->partitions,t->bytes,t->records,ud);pthread_mutex_unlock(&s->mu);}uint64_t stream_partition_count(StreamStore*s){uint64_t n=0;pthread_mutex_lock(&s->mu);for(StreamTopic*t=s->topics;t;t=t->next)n+=t->partitions;pthread_mutex_unlock(&s->mu);return n;}uint64_t stream_retention_bytes(StreamStore*s){uint64_t n=0;pthread_mutex_lock(&s->mu);for(StreamTopic*t=s->topics;t;t=t->next)n+=t->bytes;pthread_mutex_unlock(&s->mu);return n;}void stream_group_foreach_stats(StreamStore*s,StreamGroupStatsFn fn,void*ud){if(!s||!fn)return;pthread_mutex_lock(&s->mu);uint64_t now=mono_ms();for(StreamTopic*t=s->topics;t;t=t->next)for(StreamGroup*g=t->groups;g;g=g->next){group_reap_locked(g,now);fn(t->name,t->len,g->name,g->len,g->generation,g->member_count,ud);}pthread_mutex_unlock(&s->mu);}
int stream_group_member_snapshot(StreamStore*s,const char*n,uint32_t l,const char*g,uint32_t gl,StreamGroupMemberSnapshotFn fn,void*ud,uint64_t*out_generation,uint32_t*out_member_count){if(!s||!g||!gl||gl>STREAM_GROUP_MAX||!fn)return-1;pthread_mutex_lock(&s->mu);StreamTopic*t=topic(s,n,l);StreamGroup*x=t?group(s,t,g,gl,0):NULL;if(!t||!x){pthread_mutex_unlock(&s->mu);return 0;}uint64_t now=mono_ms(),owners[STREAM_GROUP_MEMBERS_MAX];uint32_t count=group_owners_locked(x,now,owners);if(out_generation)*out_generation=x->generation;if(out_member_count)*out_member_count=count;for(uint32_t i=0;i<count;i++){uint32_t assigned=0;uint64_t deadline=0;for(uint32_t p=0;p<t->partitions;p++)if(owners[p%count]==owners[i])assigned++;for(StreamMember*m=x->members;m;m=m->next)if(m->owner==owners[i]){deadline=m->deadline_ms;break;}fn(i,assigned,deadline>now?deadline-now:0,ud);}pthread_mutex_unlock(&s->mu);return 1;}
uint64_t stream_group_count(StreamStore*s){uint64_t n=0;pthread_mutex_lock(&s->mu);for(StreamTopic*t=s->topics;t;t=t->next)for(StreamGroup*g=t->groups;g;g=g->next)n++;pthread_mutex_unlock(&s->mu);return n;}uint64_t stream_group_member_count(StreamStore*s){uint64_t n=0,now=mono_ms();pthread_mutex_lock(&s->mu);for(StreamTopic*t=s->topics;t;t=t->next)for(StreamGroup*g=t->groups;g;g=g->next){group_reap_locked(g,now);n+=g->member_count;}pthread_mutex_unlock(&s->mu);return n;}int stream_persistence_failed(StreamStore*s){pthread_mutex_lock(&s->mu);int n=s->failed;pthread_mutex_unlock(&s->mu);return n;}
int stream_checkpoint_maybe(StreamStore*s){if(!s)return-1;pthread_mutex_lock(&s->mu);if(s->failed||s->fd<0){pthread_mutex_unlock(&s->mu);return-1;}uint64_t before=s->wal_bytes;int rc=compact_maybe_locked(s);int changed=rc?0:s->wal_bytes<before;pthread_mutex_unlock(&s->mu);return rc?-1:changed;}
void stream_debug_recount(StreamStore*s,uint64_t*full_records,uint64_t*full_live,uint64_t*incr_live){if(!s)return;pthread_mutex_lock(&s->mu);uint64_t records=0,live=0;for(StreamTopic*t=s->topics;t;t=t->next){live+=22u+t->len+(t->id_persisted?identity_live(t):0);for(uint32_t p=0;p<t->partitions;p++)for(StreamRecord*r=t->parts[p].head;r;r=r->next){records++;live+=record_live(t,r);}for(StreamGroup*g=t->groups;g;g=g->next)live+=(uint64_t)t->partitions*(25u+t->len+g->len);}if(full_records)*full_records=records;if(full_live)*full_live=live;if(incr_live)*incr_live=s->live_bytes;pthread_mutex_unlock(&s->mu);}
